#!/usr/bin/env python3
"""Create a PostgreSQL benchmark database and load a billion compact rows.

The loader is intentionally resumable. Each batch and its progress marker commit
in the same transaction, so rerunning the script continues from the last fully
committed batch. The primary-key index is built after loading for throughput.
"""

from __future__ import annotations

import argparse
import getpass
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import time


DEFAULT_DATABASE = "database_testing"
DEFAULT_TABLE = "benchmark_rows"
DEFAULT_ROWS = 1_000_000_000
DEFAULT_BATCH_SIZE = 5_000_000
DEFAULT_PSQL = Path(r"C:\Program Files\PostgreSQL\18\bin\psql.exe")
MAX_INTEGER = 2_147_483_647


def identifier(value: str) -> str:
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]{0,39}", value):
        raise argparse.ArgumentTypeError(
            "must start with a letter or underscore, contain only letters, "
            "numbers, and underscores, and be at most 40 characters"
        )
    return value


def quote_ident(value: str) -> str:
    return f'"{value}"'


def sql_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


class Postgres:
    def __init__(
        self,
        psql: Path,
        host: str,
        port: int,
        user: str,
        password: str,
    ) -> None:
        self.psql = psql
        self.host = host
        self.port = port
        self.user = user
        self.environment = os.environ.copy()
        self.environment["PGPASSWORD"] = password

    def run(self, database: str, sql: str, *, capture: bool = False) -> str:
        command = [
            str(self.psql),
            "-X",
            "--no-psqlrc",
            "--set",
            "ON_ERROR_STOP=1",
            "--host",
            self.host,
            "--port",
            str(self.port),
            "--username",
            self.user,
            "--dbname",
            database,
            "--quiet",
        ]
        if capture:
            command.extend(["--tuples-only", "--no-align", "--field-separator", "|"])

        result = subprocess.run(
            command,
            input=sql,
            text=True,
            encoding="utf-8",
            env=self.environment,
            capture_output=capture,
            check=False,
        )
        if result.returncode != 0:
            detail = result.stderr.strip() if capture else "psql reported an error"
            raise RuntimeError(detail)
        return result.stdout.strip() if capture else ""


def resolve_psql(requested: str | None) -> Path:
    if requested:
        path = Path(requested)
    elif shutil.which("psql"):
        path = Path(shutil.which("psql") or "")
    else:
        path = DEFAULT_PSQL
    if not path.is_file():
        raise FileNotFoundError(f"psql was not found at {path}")
    return path


def create_database_if_needed(pg: Postgres, database: str) -> None:
    exists = pg.run(
        "postgres",
        f"SELECT 1 FROM pg_database WHERE datname = {sql_literal(database)};",
        capture=True,
    )
    if exists == "1":
        print(f"Database {database!r} already exists.")
        return
    print(f"Creating database {database!r}...")
    pg.run("postgres", f"CREATE DATABASE {quote_ident(database)};")


def verify_postgresql_18(pg: Postgres, database: str) -> None:
    version_number = int(pg.run(database, "SHOW server_version_num;", capture=True))
    if not 180000 <= version_number < 190000:
        raise RuntimeError(
            f"This benchmark requires PostgreSQL 18; server_version_num is {version_number}."
        )


def initialize_schema(pg: Postgres, database: str, table: str, target_rows: int) -> int:
    table_ident = quote_ident(table)

    pg.run(
        database,
        f"""
        CREATE TABLE IF NOT EXISTS {table_ident} (
            id integer GENERATED BY DEFAULT AS IDENTITY,
            group_id smallint NOT NULL CHECK (group_id BETWEEN 0 AND 100),
            data_value smallint NOT NULL,
            start_at timestamp without time zone NOT NULL,
            end_at timestamp without time zone NOT NULL,
            CHECK (end_at >= start_at)
        );

        CREATE TABLE IF NOT EXISTS benchmark_load_state (
            table_name text PRIMARY KEY,
            target_rows bigint NOT NULL CHECK (target_rows > 0),
            loaded_rows bigint NOT NULL DEFAULT 0 CHECK (loaded_rows >= 0),
            started_at timestamp with time zone NOT NULL DEFAULT clock_timestamp(),
            updated_at timestamp with time zone NOT NULL DEFAULT clock_timestamp()
        );

        INSERT INTO benchmark_load_state (table_name, target_rows)
        SELECT {sql_literal(table)}, {target_rows}
        WHERE NOT EXISTS (SELECT FROM {table_ident} LIMIT 1)
        ON CONFLICT (table_name) DO NOTHING;
        """,
    )

    state = pg.run(
        database,
        f"""
        SELECT target_rows, loaded_rows
        FROM benchmark_load_state
        WHERE table_name = {sql_literal(table)};
        """,
        capture=True,
    )
    if not state:
        raise RuntimeError(
            f"Table {table!r} contains rows but has no loader state. Refusing to "
            "guess where a resumable load should begin."
        )
    stored_target, loaded_rows = (int(part) for part in state.split("|"))
    if stored_target != target_rows:
        raise RuntimeError(
            f"Existing load state targets {stored_target:,} rows, but this run requested "
            f"{target_rows:,}. Use the original target or choose another table/database."
        )
    return loaded_rows


def batch_sql(table: str, first_id: int, last_id: int) -> str:
    table_ident = quote_ident(table)
    table_literal = sql_literal(table)
    positive_mask = 9_223_372_036_854_775_807
    ten_years_seconds = 315_576_000
    thirty_days_seconds = 2_592_000

    # hashint8extended gives deterministic, uniformly distributed test values.
    # Explicit IDs make batches gapless and resumable; the identity sequence is
    # synchronized after loading so subsequent inserts still auto-increment.
    return f"""
    BEGIN;
    INSERT INTO {table_ident} (id, group_id, data_value, start_at, end_at)
    OVERRIDING SYSTEM VALUE
    SELECT
        g::integer,
        (((hashint8extended(g, 11) & {positive_mask}) % 101))::smallint,
        ((((hashint8extended(g, 23) & {positive_mask}) % 65536) - 32768))::smallint,
        timestamp '2015-01-01 00:00:00'
            + (((hashint8extended(g, 37) & {positive_mask}) % {ten_years_seconds}))
              * interval '1 second',
        timestamp '2015-01-01 00:00:00'
            + (((hashint8extended(g, 37) & {positive_mask}) % {ten_years_seconds}))
              * interval '1 second'
            + (((hashint8extended(g, 53) & {positive_mask}) % {thirty_days_seconds + 1}))
              * interval '1 second'
    FROM generate_series({first_id}::bigint, {last_id}::bigint) AS generated(g);

    DO $guard$
    DECLARE
        updated_count integer;
    BEGIN
        UPDATE benchmark_load_state
        SET loaded_rows = {last_id}, updated_at = clock_timestamp()
        WHERE table_name = {table_literal} AND loaded_rows = {first_id - 1};
        GET DIAGNOSTICS updated_count = ROW_COUNT;
        IF updated_count <> 1 THEN
            RAISE EXCEPTION 'Load-state concurrency check failed for {table}';
        END IF;
    END
    $guard$;
    COMMIT;
    """


def relation_size(pg: Postgres, database: str, table: str) -> int:
    result = pg.run(
        database,
        f"SELECT pg_total_relation_size({sql_literal('public.' + table)});",
        capture=True,
    )
    return int(result)


def human_bytes(value: float) -> str:
    units = ["B", "KiB", "MiB", "GiB", "TiB"]
    unit = units[0]
    for unit in units:
        if value < 1024 or unit == units[-1]:
            return f"{value:.1f} {unit}"
        value /= 1024
    raise AssertionError("unreachable")


def human_duration(seconds: float) -> str:
    seconds = max(0, int(seconds))
    hours, remainder = divmod(seconds, 3600)
    minutes, seconds = divmod(remainder, 60)
    if hours:
        return f"{hours}h {minutes:02d}m"
    if minutes:
        return f"{minutes}m {seconds:02d}s"
    return f"{seconds}s"


def load_rows(
    pg: Postgres,
    database: str,
    table: str,
    target_rows: int,
    batch_size: int,
    loaded_rows: int,
) -> None:
    if loaded_rows >= target_rows:
        print(f"All {target_rows:,} rows are already loaded.")
        return

    starting_rows = loaded_rows
    started = time.monotonic()
    while loaded_rows < target_rows:
        first_id = loaded_rows + 1
        last_id = min(target_rows, loaded_rows + batch_size)
        batch_started = time.monotonic()
        pg.run(database, batch_sql(table, first_id, last_id))
        loaded_rows = last_id

        elapsed = time.monotonic() - started
        batch_elapsed = time.monotonic() - batch_started
        rows_this_run = loaded_rows - starting_rows
        rate = rows_this_run / elapsed if elapsed else 0
        remaining = (target_rows - loaded_rows) / rate if rate else 0
        size = relation_size(pg, database, table)
        print(
            f"Loaded {loaded_rows:,}/{target_rows:,} "
            f"({loaded_rows / target_rows:6.2%}); "
            f"batch {batch_elapsed:.1f}s; {rate:,.0f} rows/s; "
            f"table {human_bytes(size)}; ETA {human_duration(remaining)}",
            flush=True,
        )


def finalize_table(
    pg: Postgres,
    database: str,
    table: str,
    target_rows: int,
    maintenance_work_mem: str,
) -> None:
    table_ident = quote_ident(table)
    primary_key = quote_ident(f"{table}_pkey")
    sequence = pg.run(
        database,
        f"SELECT pg_get_serial_sequence({sql_literal('public.' + table)}, 'id');",
        capture=True,
    )
    if not sequence:
        raise RuntimeError("Could not find the identity sequence for the id column.")

    pg.run(
        database,
        f"SELECT setval({sql_literal(sequence)}, {target_rows}, true);",
        capture=True,
    )

    has_primary_key = pg.run(
        database,
        f"""
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = {sql_literal('public.' + table)}::regclass
          AND contype = 'p';
        """,
        capture=True,
    )
    if has_primary_key != "1":
        print("Building the primary-key index (this is the final long-running step)...")
        pg.run(
            database,
            f"""
            SET maintenance_work_mem = {sql_literal(maintenance_work_mem)};
            CREATE UNIQUE INDEX IF NOT EXISTS {primary_key} ON {table_ident} (id);
            ALTER TABLE {table_ident}
                ADD CONSTRAINT {primary_key} PRIMARY KEY USING INDEX {primary_key};
            """,
        )

    print("Running ANALYZE...")
    pg.run(database, f"ANALYZE {table_ident};")


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--database", type=identifier, default=DEFAULT_DATABASE)
    parser.add_argument("--table", type=identifier, default=DEFAULT_TABLE)
    parser.add_argument("--rows", type=int, default=DEFAULT_ROWS)
    parser.add_argument("--batch-size", type=int, default=DEFAULT_BATCH_SIZE)
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=5432)
    parser.add_argument("--user", default="postgres")
    parser.add_argument(
        "--password",
        help="Database password; prefer the PGPASSWORD environment variable or prompt.",
    )
    parser.add_argument("--psql", help="Path to psql.exe if it is not on PATH.")
    parser.add_argument("--maintenance-work-mem", default="1GB")
    parser.add_argument(
        "--yes",
        action="store_true",
        help="Skip the interactive confirmation before loading.",
    )
    arguments = parser.parse_args()
    if not 0 < arguments.rows <= MAX_INTEGER:
        parser.error(f"--rows must be between 1 and {MAX_INTEGER:,}")
    if arguments.batch_size <= 0:
        parser.error("--batch-size must be greater than zero")
    if not 1 <= arguments.port <= 65535:
        parser.error("--port must be between 1 and 65535")
    return arguments


def main() -> int:
    args = parse_arguments()
    psql = resolve_psql(args.psql)
    password = args.password or os.environ.get("PGPASSWORD")
    if not password:
        password = getpass.getpass(f"Password for PostgreSQL user {args.user}: ")

    if not args.yes:
        answer = input(
            f"Create/use database {args.database!r} and load {args.rows:,} rows "
            f"into {args.table!r}? [y/N] "
        )
        if answer.strip().lower() not in {"y", "yes"}:
            print("Cancelled.")
            return 0

    pg = Postgres(psql, args.host, args.port, args.user, password)
    create_database_if_needed(pg, args.database)
    verify_postgresql_18(pg, args.database)
    loaded_rows = initialize_schema(pg, args.database, args.table, args.rows)
    print(f"Starting from {loaded_rows:,} committed rows.")
    load_rows(
        pg,
        args.database,
        args.table,
        args.rows,
        args.batch_size,
        loaded_rows,
    )
    finalize_table(
        pg,
        args.database,
        args.table,
        args.rows,
        args.maintenance_work_mem,
    )
    final_size = relation_size(pg, args.database, args.table)
    print(f"Finished. Final table and index size: {human_bytes(final_size)}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        print("\nInterrupted. Rerun the same command to resume committed batches.")
        raise SystemExit(130)
    except (FileNotFoundError, RuntimeError) as error:
        print(f"Error: {error}", file=sys.stderr)
        raise SystemExit(1)
